# This is a basic workflow that is manually triggered

name: Build Wug

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Msg      
      run: echo "Running git Clone"
      
    - name: Remove existing Repo
      run: Remove-Item c:\Work  -Force  -Recurse -ErrorAction SilentlyContinue
      
    - name: Clone Repo
      run: git clone -branch github_cloud_poc git@github.bedford.progress.com:aestrada/WUG.git C:/Work/WUG/Main     

    - name: Run Devbuild
      working-directory: C:\work\WUG\Main\Source\DevBuildTools
      shell: cmd
      run: DevBuild.bat

    # Run unit testcases with report generation
              
    - name: Parse Trx files
      uses: NasAmin/trx-parser@v0.0.3
      id: trx-parser
      with:
        TRX_PATH:  C:\Work\WUG\Main\Source\DevBuildTools\UnitTests\TestResults #This should be the path to your TRX files
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Download CodeCoverage Report
      uses: actions/upload-artifact@v2
      with:
         name: CodeCoverage
         path: C:\Work\WUG\Main\Source\DevBuildTools\UnitTests\CoverageReport.html
   
