# This is a basic workflow to help you get started with Actions

name: Push unit Test result

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pushResult:
    runs-on: self-hosted
    steps:
      - name: Parse Trx files
        uses: NasAmin/trx-parser@v0.0.3
        id: trx-parser
        with:
          TRX_PATH:  C:\Work\WUG\Main\Source\DevBuildTools\UnitTests\TestResults #This should be the path to your TRX files
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download CodeCoverage Report
        uses: actions/upload-artifact@v2
        with:
           name: CodeCoverage
           path: C:\Work\WUG\Main\Source\DevBuildTools\UnitTests\TestResults\CoverageReport.html 
