# This is a basic workflow to help you get started with Actions

name: Push unit Test result

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.6
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: C:\Work\WUG\Main\Source\DevBuildTools\UnitTests\TestResults\MSTestResults-Core.Rest.UnitTests.trx
